### PR TITLE
Rebuild static sources

### PR DESCRIPTION
**Pull request by samcome**
Rebuild with gulp the new static files

Part of #87 and #89

add folders in kernel/static
  css
  fonts
  img
  js

delete folder kernel/static/kernel
  old files not use

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Je vois beaucoup de 404:

╭╴ (feature-89 $%=) [virt]╶╮
╰ 1, jeff@siegfried:django $ python manage.py runserver
Performing system checks...

System check identified some issues:

WARNINGS:
locomo_auth.EmailRegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
registration.RegistrationProfile.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
May 13, 2015 - 15:15:41
Django version 1.8.1, using settings 'locomokidz.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
/home/jeff/src/locomokidz/django/venv/lib/python3.4/site-packages/django/templatetags/future.py:25: RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning)

[13/May/2015 15:15:49]"GET / HTTP/1.1" 200 14589
[13/May/2015 15:15:49]"GET /static/kernel/base.css HTTP/1.1" 404 1658
[13/May/2015 15:15:50]"GET /static/kernel/modernizr-2.6.2.min.js HTTP/1.1" 404 1700
[13/May/2015 15:15:50]"GET /static/kernel/lkztheme.css HTTP/1.1" 404 1670
[13/May/2015 15:15:50]"GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 20001
[13/May/2015 15:15:50]"GET /static/kernel/landing.css HTTP/1.1" 404 1667
[13/May/2015 15:15:50]"GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12271
[13/May/2015 15:15:50]"GET /static/kernel/res/lkzlogo.png HTTP/1.1" 404 1679
[13/May/2015 15:15:52]"GET /static/kernel/res/fb-round.png HTTP/1.1" 404 1682
[13/May/2015 15:15:52]"GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404
[13/May/2015 15:15:52]"GET /static/kernel/res/twitter-round.png HTTP/1.1" 404 1697
[13/May/2015 15:15:52]"GET /static/kernel/lkztheme.css HTTP/1.1" 404 1670
[13/May/2015 15:15:52]"GET /static/kernel/landing.css HTTP/1.1" 404 1667
[13/May/2015 15:15:53]"GET /static/kernel/res/lkzlogo.png HTTP/1.1" 404 1679
[13/May/2015 15:15:53]"GET /static/kernel/res/fb-round.png HTTP/1.1" 404 1682
[13/May/2015 15:15:53]"GET /static/kernel/res/twitter-round.png HTTP/1.1" 404 1697
[13/May/2015 15:15:55]"GET /favicon.ico HTTP/1.1" 404 12310
[13/May/2015 15:15:56]"GET /favicon.ico HTTP/1.1" 404 12310
^C╭╴ (feature-89 $%=) [virt]╶╮
╰ jeff@siegfried:django $

**Comment by samcome** [comment]
C'est lié avec: HTML rewriting templates #95

**Comment by JeffAbrahamson** [comment]
ok, tu veux mettre à jour la branche feature-89 pour qu'elle marche?

**Comment by samcome** [comment]
à part un merge avec le master je vois pas comment faire autrement.

**Comment by JeffAbrahamson** [comment]
Tu merges master dans ta branche.

**Comment by samcome** [comment]
C'est fait.

**Comment by JeffAbrahamson** [comment]
Merci !

**Pull request merged**
