### PR TITLE
base tools frontend + base html

### PR DESCRIPTION
**Pull request by samcome**
## Adding files for the frontend development (task automation)
**See README.dev for deployment, section: Only for FrontEnd Dev**

* package.json (dependencies)
* gulfile.js (project config -> work with command line gulp)
* folder 'src'
	* 	fonts (+bootstrap)
	* 	img
	* 	jss (+bootstrap)
	* 	less (+bootstrap)

### Static folder
* kernel/static/
	* 	css
	* 	fonts
	* 	img
	* 	js
		* 	apple-touch-icon.png
		* 	favicon.ico
		* 	humans.txt
		* 	robots.txt

### html files
* kernel/templates/kernel/*.html	
* kernel/templates/registration/*.html	
* kernel/templates/trip/*.html	
* templates/registration/*.html

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
Ce PR est obsolète ?

**Comment by samcome** [comment]
Maintenant oui.

Samuel Frémondière

samcome@icloud.com
Tél. 0678155348

**Comment by JeffAbrahamson** [comment]
OK.  Je peux te laisser supprimer les branches et PR qui ne sont plus utiliser?

**Comment by samcome** [comment]
Ok je m'en occupe

Samuel Frémondière

samcome@icloud.com
Tél. 0678155348

**Pull request closed without merging**
